In [54]:
# pandas is python lib
# pandas lib used of data manupulation 

# how to import

import pandas as pd

In [55]:
dicts = {
    
    "Name" : ["Salman khan","Ranbhir","Ajay devgan","Ram Charan","Prabhas"],
    "Age"  :[61,22,33,43,54,],
    "Height" :[5.6,5.1,6.4,7.2,5.1],
    "Salary" : [1000,2323,343344,2222,2233]
}

In [56]:
# method 1: DataFrame --- convert the data into Table form

df=pd.DataFrame(dicts)
df

          Name  Age  Height  Salary
0  Salman khan   61     5.6    1000
1      Ranbhir   22     5.1    2323
2  Ajay devgan   33     6.4  343344
3   Ram Charan   43     7.2    2222
4      Prabhas   54     5.1    2233

In [57]:
# load the dataset

df=pd.read_csv("C:/Users/ssart/NareshIT/Full Stack Data scinece course 5 PM\Datasets\dataset.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [58]:
# method 3: head()  -- top five rows display
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [59]:
# method 4: tail() last five rows

df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [60]:
# method 5 : sample()   - display random rows

df.sample(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
67,45,0,1,130,234,0,0,175,0,0.6,1,0,2,1
101,59,1,3,178,270,0,0,145,0,4.2,0,0,3,1
295,63,1,0,140,187,0,0,144,1,4.0,2,2,3,0
195,59,1,0,170,326,0,0,140,1,3.4,0,0,3,0
40,51,0,2,140,308,0,0,142,0,1.5,2,1,2,1

In [61]:
# method 6: shape check the size the datasets
df.shape

(303, 14)

In [62]:
# method 7: info() check information of datasets
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [63]:
# method 8: columns check the columns name 

df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [64]:
# method 9 : describe()  statistical summary of the numerical column

df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [65]:
# method 10 : isnull() check the missing value

df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [66]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [67]:
# method 11: select the single column

df["age"]

0      63
1      37
2      41
3      56
4      57
       ..
298    57
299    45
300    68
301    57
302    57
Name: age, Length: 303, dtype: int64

In [68]:
# method 12 : select the multiple columns 

two_col=df[["age","sex"]]
two_col

     age  sex
0     63    1
1     37    1
2     41    0
3     56    1
4     57    0
..   ...  ...
298   57    0
299   45    1
300   68    1
301   57    1
302   57    0

[303 rows x 2 columns]

In [69]:
# method 13 : value_counts()  check the specific columns value count

df['age'].value_counts(dropna = True)

58    19
57    17
54    16
59    14
52    13
51    12
62    11
60    11
44    11
56    11
64    10
41    10
63     9
67     9
65     8
43     8
45     8
55     8
42     8
61     8
53     8
46     7
48     7
66     7
50     7
49     5
47     5
70     4
39     4
35     4
68     4
38     3
71     3
40     3
69     3
34     2
37     2
29     1
74     1
76     1
77     1
Name: age, dtype: int64

In [70]:
# method 15 : copy the datasets into another variable

df2=df.copy()

In [71]:
# method 16 : drop() = drop the columns

df.drop("age",axis = 1,inplace = True)

In [72]:
df

,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [73]:
# method 17 : multi columns drop 

df.drop(columns = ["sex","chol"],axis = True,inplace= True)

In [74]:
df.drop(df[["cp","fbs"]],axis = True,inplace= True)

In [75]:
# method 18 : drop_duplicates() drop duplicated rows  

df.drop_duplicates(inplace= True)

In [76]:
df

     trestbps  restecg  thalach  exang  oldpeak  slope  ca  thal  target
0         145        0      150      0      2.3      0   0     1       1
1         130        1      187      0      3.5      0   0     2       1
2         130        0      172      0      1.4      2   0     2       1
3         120        1      178      0      0.8      2   0     2       1
4         120        1      163      1      0.6      2   0     2       1
..        ...      ...      ...    ...      ...    ...  ..   ...     ...
298       140        1      123      1      0.2      1   0     3       0
299       110        1      132      0      1.2      1   0     3       0
300       144        1      141      0      3.4      1   2     3       0
301       130        1      115      1      1.2      1   1     3       0
302       130        0      174      0      0.0      1   1     2       0

[301 rows x 9 columns]

In [77]:
# method 19 : drop_dupliactes(subset =["col_name"])  : specific column rows drop 

df.drop_duplicates(subset = ["oldpeak"],inplace = True)

In [78]:
# method 20 : rename : change the columns name

df.rename(columns = {"target":"Result"},inplace=True)

In [79]:
df.columns

Index(['trestbps', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca',
       'thal', 'Result'],
      dtype='object')

In [80]:
for i in df.columns:
    c=i.title()
    print(c)

Trestbps
Restecg
Thalach
Exang
Oldpeak
Slope
Ca
Thal
Result

In [81]:
df.columns

Index(['trestbps', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca',
       'thal', 'Result'],
      dtype='object')

In [82]:
df.columns = map(lambda x: x.title(),df.columns)

In [83]:
df.columns

Index(['Trestbps', 'Restecg', 'Thalach', 'Exang', 'Oldpeak', 'Slope', 'Ca',
       'Thal', 'Result'],
      dtype='object')

In [84]:
df.head()

   Trestbps  Restecg  Thalach  Exang  Oldpeak  Slope  Ca  Thal  Result
0       145        0      150      0      2.3      0   0     1       1
1       130        1      187      0      3.5      0   0     2       1
2       130        0      172      0      1.4      2   0     2       1
3       120        1      178      0      0.8      2   0     2       1
4       120        1      163      1      0.6      2   0     2       1

In [85]:
# method 21 : astype() chnage datatype of columns 



df['Oldpeak']=df['Oldpeak'].astype("int")

df['Oldpeak']

0      2
1      3
2      1
3      0
4      0
5      0
6      1
7      0
8      0
9      1
10     1
11     0
13     1
14     1
17     2
18     1
42     3
76     2
97     0
98     1
101    4
108    1
116    2
125    0
143    0
147    0
167    3
169    3
173    3
178    2
187    2
193    2
195    3
204    6
220    4
221    5
240    2
244    2
259    3
291    4
Name: Oldpeak, dtype: int32

In [86]:
age = ["12","23","34","45","su23","a1","11"]

# method 22 : to_numeric  - number string convert into number

pd.to_numeric(age, errors='coerce')

array([12., 23., 34., 45., nan, nan, 11.])

In [87]:
# method 23 : fillna("value")  - fill the missing value

#df.fillna(0,inplace =True)


# syntax :df['column'] = df['column'].fillna("value")

#df['Oldpeak'] = df['Oldpeak'].fillna()

In [88]:
old_mean =int(df['Oldpeak'].mode())
old_mean

0

In [89]:
# method 24 : dropna()  - drop the missing value rows 

df.dropna(inplace = True)

In [90]:
df['Oldpeak'].notnull()

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
13     True
14     True
17     True
18     True
42     True
76     True
97     True
98     True
101    True
108    True
116    True
125    True
143    True
147    True
167    True
169    True
173    True
178    True
187    True
193    True
195    True
204    True
220    True
221    True
240    True
244    True
259    True
291    True
Name: Oldpeak, dtype: bool

In [91]:
# Method 25 : replace ()   replace the old value with new value

#df["col"].replace({"old":"new"},inplace = True)


df.replace({"Result":{"1":"Yes","0":"No"}})

     Trestbps  Restecg  Thalach  Exang  Oldpeak  Slope  Ca  Thal  Result
0         145        0      150      0        2      0   0     1       1
1         130        1      187      0        3      0   0     2       1
2         130        0      172      0        1      2   0     2       1
3         120        1      178      0        0      2   0     2       1
4         120        1      163      1        0      2   0     2       1
5         140        1      148      0        0      1   0     1       1
6         140        0      153      0        1      1   0     2       1
7         120        1      173      0        0      2   0     3       1
8         172        1      162      0        0      2   0     3       1
9         150        1      174      0        1      2   0     2       1
10        140        1      160      0        1      2   0     2       1
11        130        1      139      0        0      2   0     2       1
13        110        0      144      1        1      1   0     2       1
14        150        0      162      0        1      2   0     2       1
17        150        1      114      0        2      0   0     2       1
18        150        1      171      0        1      2   0     2       1
42        104        0      148      1        3      1   0     2       1
76        125        0      166      0        2      1   0     2       1
97        108        1      147      0        0      2   3     3       1
98        130        1      162      0        1      2   1     2       1
101       178        0      145      0        4      0   0     3       1
108       120        1      162      0        1      2   0     2       1
116       130        0      168      0        2      1   0     2       1
125       118        1      192      0        0      2   0     2       1
143       106        1      142      0        0      2   2     2       1
147       150        1      171      0        0      2   0     2       1
167       140        0      160      0        3      0   2     2       0
169       140        0      155      1        3      0   0     3       0
173       132        0      173      0        3      2   2     3       0
178       120        0      120      1        2      1   0     3       0
187       124        0      109      1        2      1   1     3       0
193       145        0      142      1        2      1   2     3       0
195       170        0      140      1        3      0   0     3       0
204       160        0      145      0        6      0   3     3       0
220       150        0      154      0        4      1   3     3       0
221       140        1      111      1        5      0   0     3       0
240       160        1      112      1        2      1   1     3       0
244       132        0      105      1        2      1   1     1       0
259       120        1      182      1        3      1   0     3       0
291       114        2      140      0        4      0   3     1       0

In [92]:
df = pd.read_csv("C:\\Users\\ssart\\Downloads\\customer_churn (1).csv")
df

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
0,56,NaN,770.887470,29,84.828689,143,90,1,Male,South,1
1,69,53051.954538,622.025467,41,133.943805,72,96,4,Female,East,1
2,46,38654.738821,665.727931,36,114.993023,155,88,3,Male,North,1
3,32,28666.194356,715.281358,29,153.875284,76,110,2,Male,South,0
4,60,40301.406736,NaN,27,115.391031,168,99,2,Male,East,1
...,...,...,...,...,...,...,...,...,...,...,...
995,60,56292.986659,751.728246,26,149.322171,120,93,4,Male,West,0
996,64,36687.617333,556.297594,40,44.289513,172,3,4,Male,South,1
997,62,43438.125495,698.504304,33,132.459634,3,52,2,Male,East,0
998,35,60835.720367,607.589743,49,72.489390,341,74,3,Male,West,1
999,55,44407.502719,770.356453,36,104.107070,127,60,4,Female,South,1

In [93]:
# method 25: replace 

df.replace({'gender':{"Male":1,"Female":0}},inplace = True)
df.head()

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
0,56,NaN,770.887470,29,84.828689,143,90,1,1,South,1
1,69,53051.954538,622.025467,41,133.943805,72,96,4,0,East,1
2,46,38654.738821,665.727931,36,114.993023,155,88,3,1,North,1
3,32,28666.194356,715.281358,29,153.875284,76,110,2,1,South,0
4,60,40301.406736,NaN,27,115.391031,168,99,2,1,East,1

In [94]:
# method 26: sort_values("col")  - sort the columns value 

# syntax : df.sort_value("col_name")

df.sort_values("age")

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
499,18,56381.863427,553.426728,31,79.289428,270,76,2,1,East,0
101,18,84060.392867,654.317589,26,136.519956,204,16,3,1,North,1
726,18,28960.920923,628.085938,38,125.983918,34,30,5,1,North,1
850,18,46798.356936,543.748838,35,101.329648,240,72,3,1,West,0
845,18,47838.686664,622.903021,27,57.648520,284,100,5,1,North,1
...,...,...,...,...,...,...,...,...,...,...,...
390,69,29310.211580,628.437600,26,115.414367,277,55,2,1,West,0
218,69,42159.154692,674.544107,34,101.854544,40,77,4,1,West,1
469,69,55280.830948,738.334505,37,174.404636,81,26,5,1,West,0
520,69,50894.455549,594.530606,26,143.495668,230,86,2,1,North,1
892,69,72067.554912,728.217917,30,172.909779,30,10,4,0,East,1

In [95]:
# method 28 : groupby()

#df.groupby("colum_wise")["another_col"].agg_function


df.groupby("region")['age'].mean()

region
East     43.022222
North    43.361868
South    44.265918
West     44.525896
Name: age, dtype: float64

In [96]:
# method 29: transform()

df['Age_range']=df["age"].transform(lambda x :"Old_person" if x > 45 else "Young person")
df.head()

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn,Age_range
0,56,NaN,770.887470,29,84.828689,143,90,1,1,South,1,Old_person
1,69,53051.954538,622.025467,41,133.943805,72,96,4,0,East,1,Old_person
2,46,38654.738821,665.727931,36,114.993023,155,88,3,1,North,1,Old_person
3,32,28666.194356,715.281358,29,153.875284,76,110,2,1,South,0,Young person
4,60,40301.406736,NaN,27,115.391031,168,99,2,1,East,1,Old_person

In [97]:
# method 30 : apply()

df['platform_left_status']=df['age'].apply(lambda x : "left" if x > 50 else "not left")

In [98]:
df.head()

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn,Age_range,platform_left_status
0,56,NaN,770.887470,29,84.828689,143,90,1,1,South,1,Old_person,left
1,69,53051.954538,622.025467,41,133.943805,72,96,4,0,East,1,Old_person,left
2,46,38654.738821,665.727931,36,114.993023,155,88,3,1,North,1,Old_person,not left
3,32,28666.194356,715.281358,29,153.875284,76,110,2,1,South,0,Young person,not left
4,60,40301.406736,NaN,27,115.391031,168,99,2,1,East,1,Old_person,left

In [99]:
# method 31 : applymap()


df.applymap(lambda x : round(x,2))

TypeError: type str doesn't define __round__ method

In [ ]:
#method 32 : map :

df['Age_range']= df['Age_range'].map({'Old_person': '0', 'Young person': '1'})

In [ ]:
df['Age_range'].value_counts()

In [ ]:
# method 33 : nunique

df['age'].unique()

In [ ]:
# method 34 : reset_index()

df.reset_index(drop=True)

In [ ]:
# method 35 : select_dtypes()  - select the columns types wise 

numerical_col = df.select_dtypes(include ="number")

intger_col  = df.select_dtypes(include ="int64")

float_col  = df.select_dtypes(include = "float64")

cat_col = df.select_dtypes(include = "object")

In [ ]:
df['Age_range'].dtypes

In [ ]:
# handled the date columns 


# first  : str column convert into the date

df = pd.DataFrame({'date': ['2024-01-15', '2024-02-20', '2024-03-25']}) 

df

In [ ]:
# method 36 : to_datetime()

pd.to_datetime(df['date'])

In [ ]:
# Handle Different Date Formats 

df = pd.DataFrame({'date': [ 
    '2024-01-15',      # YYYY-MM-DD 
    '15/01/2024',      # DD/MM/YYYY 
    '01-15-2024',      # MM-DD-YYYY 
    'Jan 15 2024',     # Month name 
    '15 January 2024', # Full month name 
    '20240115'         # Compact format 
]}) 

df.dtypes

In [ ]:
# # Auto detect format

df['date'] = pd.to_datetime(df['date'], dayfirst=True, infer_datetime_format=True)
df['date']

In [ ]:
#  Convert with Specific Format 

df = pd.DataFrame({'date': ['2024-01-15', '2024-02-20', '2024-03-25']}) 
df.dtypes

In [ ]:

df['date'] = pd.to_datetime(df['date'])
df.dtypes

In [ ]:
df

In [ ]:
# change the datetime formate 

df['date'] = df['date'].dt.strftime("%m-%d-%Y")
df.dtypes

In [ ]:
df

In [ ]:
df.dtypes

In [ ]:

df['date'] = pd.to_datetime(df['date'])
df

In [ ]:
# extract the month from the date column 
df['month']=df['date'].dt.month

In [ ]:
# extract the year from the date column 
df['year']=df['date'].dt.year

In [ ]:
# extract the day from the date column
df['day'] = df['date'].dt.day

In [ ]:
df

In [ ]:
# make the data frame 

df = pd.DataFrame({"Price" :["$10,000","$20,000","$30,000","$40,000"]})
df.dtypes

In [ ]:
df['Price']=df['Price'].str.replace("$","").str.strip()

In [ ]:
# replace the comma 
df['Price']=df['Price'].str.replace(",","").str.strip()

In [ ]:
df

In [ ]:
# convert the column into numerical 

df['Price']=pd.to_numeric(df['Price'],errors = "coerce")

In [ ]:
# change the type of Price column 

df['Price'] =df['Price'].astype("int64")

In [ ]:
df.dtypes

In [ ]:
num ="10000"

In [ ]:
# handled the outlier 

df = pd.DataFrame({"Age" : [32,43,23,45,54,23,45,129,31,180,10,2]})
df

In [ ]:
# detect the outlier 

Q3 =df['Age'].quantile(0.75)
Q1 = df['Age'].quantile(0.25)

# find the IQR

IQR = Q3 - Q1


# find the lowe bound and upper bound 

lower_bound = Q1 - 1.5*IQR

upper_bound = Q3 + 1.5*IQR


# display the outlier 

outlier=  df[(df["Age"] < lower_bound) | (df["Age"] > upper_bound)]

In [ ]:
# Handled the outlier using clip method 
df["Age"]=df['Age'].clip(lower_bound,upper_bound)

In [ ]:
df

In [ ]:
# chnage the dtype of the age columns 

df['Age'] = df['Age'].astype("int64")
df